# hw08
#
# This Makefile is provided to help you organize the files
# for submission. It comes with ABSOLUTELY NO WARRANY and you
# are ultimately responsible for the files you submit.

.PHONY: all clean
all: kountdown.sml countdown.sml 
	zip hw08-handin.zip $^

clean:
	rm -f hw08-handin.zip
	rm -Rf .cm

